# Generated by Django 3.1.5 on 2021-01-24 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TheaterWinQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writing_date', models.DateField(default=django.utils.datetime_safe.datetime.now)),
                ('question_title', models.CharField(max_length=200)),
                ('question_isanswer', models.IntegerField(default=0)),
                ('question_hit', models.IntegerField(default=0)),
                ('question_groupnum', models.IntegerField(default=0)),
                ('question_sequencenum_ingroup', models.IntegerField(default=0)),
                ('question_level_ingorup', models.IntegerField(default=0)),
                ('etc_memo', models.CharField(blank=True, max_length=200)),
                ('user_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TheaterWinBookRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_date', models.DateField(blank=True, default=django.utils.datetime_safe.datetime.now)),
                ('writing_date', models.DateField(default=django.utils.datetime_safe.datetime.now)),
                ('buy_game_title', models.CharField(blank=True, max_length=200)),
                ('batting_ratio', models.FloatField(blank=True, default=0)),
                ('batting_money', models.IntegerField(blank=True, default=0)),
                ('folder_num', models.IntegerField(blank=True, default=1)),
                ('win_check', models.IntegerField(default=1)),
                ('etc_memo', models.CharField(blank=True, max_length=200)),
                ('share_check', models.IntegerField(default=0)),
                ('hit_count', models.IntegerField(blank=True, default=0)),
                ('user_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_date2', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
