# Generated by Django 3.1.5 on 2021-01-31 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TheaterWinBook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheaterWinQuestionReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writing_date', models.DateField(default=django.utils.datetime_safe.datetime.now)),
                ('question_reply_content', models.CharField(max_length=200)),
                ('question_reply_thumbup', models.IntegerField(default=0)),
                ('question_reply_thumbdown', models.IntegerField(default=0)),
                ('question_reply_warning', models.IntegerField(default=0)),
                ('reply_groupnum', models.IntegerField(default=0)),
                ('reply_sequencenum_ingroup', models.IntegerField(default=0)),
                ('reply_level_ingorup', models.IntegerField(default=0)),
                ('by_whom', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question_fk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TheaterWinBook.theaterwinquestion')),
            ],
        ),
        migrations.CreateModel(
            name='TheaterWinQuestionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_thumbup', models.IntegerField(default=0)),
                ('question_thumbdown', models.IntegerField(default=0)),
                ('question_warning', models.IntegerField(default=0)),
                ('by_whom', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question_fk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TheaterWinBook.theaterwinquestion')),
            ],
        ),
        migrations.CreateModel(
            name='TheaterWinBookRecordReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writing_date', models.DateField(default=django.utils.datetime_safe.datetime.now)),
                ('record_reply_content', models.CharField(max_length=200)),
                ('record_groupnum', models.IntegerField(default=0)),
                ('record_sequencenum_ingroup', models.IntegerField(default=0)),
                ('record_level_ingorup', models.IntegerField(default=0)),
                ('by_whom', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('record_fk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TheaterWinBook.theaterwinbookrecord')),
            ],
        ),
        migrations.CreateModel(
            name='TheaterWinBookRecordInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_thumbup', models.IntegerField(default=0)),
                ('record_thumbdown', models.IntegerField(default=0)),
                ('record_warning', models.IntegerField(default=0)),
                ('by_whom', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('record_fk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TheaterWinBook.theaterwinbookrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Full_Chatting_Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
