# Generated by Django 3.1.5 on 2021-09-04 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheaterWinBook', '0003_stock_summary_kr'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='STOCK_SUMMARY_KR',
            new_name='StockSummaryKr',
        ),
    ]
