# Generated by Django 3.1.5 on 2021-09-04 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheaterWinBook', '0005_auto_20210904_1623'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stocksummarykr',
            unique_together={('info_date', 'stock_code')},
        ),
    ]
