# Generated by Django 3.1.5 on 2021-09-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheaterWinBook', '0006_auto_20210904_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_country',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_first_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_foreign_share_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_foreign_share_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_foreign_share_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_market_sum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_share_total_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='vesting_type',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='vesting_type_detail',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='stocksummarykr',
            name='stock_code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='stocksummarykr',
            name='stock_name',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
