# Generated by Django 3.1.5 on 2021-09-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheaterWinBook', '0007_auto_20210905_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksummarykr',
            name='etc1_int',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='etc1_string',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='etc2_int',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='etc2_string',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='etc3_int',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='etc3_string',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='etc4_int',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='etc4_string',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='etc5_int',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='etc5_string',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_agency_buy_top1',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_agency_buy_top1_vol',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_agency_buy_top2',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_agency_buy_top2_vol',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_agency_buy_top3',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_agency_buy_top3_vol',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_agency_buy_top4',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_agency_buy_top4_vol',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_agency_buy_top5',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_agency_buy_top5_vol',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_agency_sell_top1',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_agency_sell_top1_vol',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_agency_sell_top2',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_agency_sell_top2_vol',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_agency_sell_top3',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_agency_sell_top3_vol',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_agency_sell_top4',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_agency_sell_top4_vol',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_agency_sell_top5',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_agency_sell_top5_vol',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_allocation_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_bps',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_close',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_eps',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_eps_guess',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_high',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_low',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_lowprice_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_maxprice_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_now',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_open',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_pbr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_per',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_per_guess',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_similar_per',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_trading_sum_agency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_trading_sum_ant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_trading_sum_foreign',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_volume_money',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummarykr',
            name='stock_volume_share',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
