# Generated by Django 3.1.5 on 2021-09-07 11:25

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('TheaterWinBook', '0008_auto_20210907_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksummarykr',
            name='stock_bps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stocksummarykr',
            name='stock_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stocksummarykr',
            name='stock_country',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='stocksummarykr',
            name='stock_eps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stocksummarykr',
            name='stock_eps_guess',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stocksummarykr',
            name='vesting_type',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='stocksummarykr',
            name='vesting_type_detail',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='stocksummarykr',
            unique_together={('info_date', 'stock_code', 'stock_country', 'vesting_type', 'vesting_type_detail')},
        ),
        migrations.CreateModel(
            name='StockIfrsKr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bat_time', models.DateTimeField(default=django.utils.datetime_safe.datetime.now)),
                ('info_date', models.DateField(default=django.utils.datetime_safe.datetime.now)),
                ('stock_code', models.CharField(max_length=5)),
                ('stock_country', models.CharField(max_length=1)),
                ('ifrs_type', models.CharField(max_length=1)),
                ('vesting_type', models.CharField(max_length=1)),
                ('vesting_type_detail', models.CharField(max_length=1)),
                ('stock_name', models.CharField(blank=True, max_length=15)),
                ('stock_revenue', models.IntegerField(blank=True, null=True)),
                ('operating_income', models.IntegerField(blank=True, null=True)),
                ('net_income', models.IntegerField(blank=True, null=True)),
                ('operating_income_ratio', models.FloatField(blank=True, null=True)),
                ('income_ratio', models.FloatField(blank=True, null=True)),
                ('roe', models.FloatField(blank=True, null=True)),
                ('debt_ratio', models.FloatField(blank=True, null=True)),
                ('quick_ratio', models.FloatField(blank=True, null=True)),
                ('reserve_ratio', models.FloatField(blank=True, null=True)),
                ('stock_eps', models.IntegerField(blank=True, null=True)),
                ('stock_per', models.FloatField(blank=True, null=True)),
                ('stock_bps', models.IntegerField(blank=True, null=True)),
                ('stock_pbr', models.FloatField(blank=True, null=True)),
                ('etc1_string', models.CharField(blank=True, max_length=1)),
                ('etc2_string', models.CharField(blank=True, max_length=1)),
                ('etc3_string', models.CharField(blank=True, max_length=1)),
                ('etc1_int', models.SmallIntegerField(blank=True, null=True)),
                ('etc2_int', models.SmallIntegerField(blank=True, null=True)),
                ('etc3_int', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('info_date', 'stock_code', 'stock_country', 'ifrs_type', 'vesting_type', 'vesting_type_detail')},
            },
        ),
    ]
